### PR TITLE
Create Pensieve

### PR DESCRIPTION
**Pull request by hyusap**
details in file!

### CODE REVIEW

**Comment by faisalsayed10** [comment]
@hyusap Great work! please gimme a few days to get to this. I'm swamped with a bunch of TestFlight submissions as of right now.

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
I love the idea. but it has a greater potential than what it currently is. I left a bunch of testflight reviews and i would love to see those features implemented and changes made before i can merge this
image

**Comment by faisalsayed10** [comment]
@hyusap great work on the redesign. left more feedback on the app

**Comment by faisalsayed10** [comment]
Please reply here when all the feedback is addressed

**Comment by hyusap** [comment]
feedback should be addressed!

**Review by faisalsayed10 — APPROVED** [review]
lgtm

**Pull request merged**
