### PR TITLE
Reopen: Sujud By Muhammad Shah

### PR DESCRIPTION
**Pull request by Babyyoda777**
Hi, 
The app is on the AppStore, link is here: https://apps.apple.com/gb/app/sujud/id1667160545

my developer account expires this week and would appreciate if I could get the grant so I can keep it going whilst Apple responds to my appeal for the TestFlight update. Just a note, I can’t run the appeal if I don’t have a paid developer account, so I really need the grant to fix the issues (unfortunately a very circular problem haha)

@faisalsayed10

### CODE REVIEW

**Comment by Babyyoda777** [comment]
Hi @faisalsayed10 sorry for the ping, but would it be possible to get the grant today? My developer subscription just expired 😭 and I referenced it in my uni application (they wanted a link)

**Review by faisalsayed10 — APPROVED** [review]
love the app, i'm down to ahead and give you the grant

**Comment by faisalsayed10** [comment]
@Babyyoda777 before I proceed with the grant, can you please do ID verification here at: https://forms.hackclub.com/eligibility?program=Cider

**Comment by faisalsayed10** [comment]
I also need these details from you, can you please DM it to me on slack?
image

**Pull request merged**
