### PR TITLE
Sujud by Muhammad Shah

### PR DESCRIPTION
**Pull request by Babyyoda777**
Hi, I am submitting my iOS app for a grant, I have been developing it for a while but wanted to get it out there properly!

### CODE REVIEW

**Review by faisalsayed10 — COMMENTED** [review]
Hi @Babyyoda777! I love the app, it's also really well-designed. However, as per talks with you in the past, you said that you're facing issues getting it successfully approved by the Apple Team. So before approving it, I would have to wait for you resolve those issues, before we can merge this and get your grant

**Comment by faisalsayed10** [comment]
@Babyyoda777 any updates?

**Comment by faisalsayed10** [comment]
Closing as stale :((

**Comment by Babyyoda777** [comment]
> Closing as stale :((

Hi sorry for the late reply! Unfortunately I got really busy with uni apps so probably am gonna have to call up Apple after then. The app is already on the AppStore but I don't have funding for the new year and my subscription expires in a week. Would it be possible to get the gift card so I can just keep it on there whilst I sort out the issues?

I want to avoid the app being removed from AppStore @faisalsayed10

**Comment by faisalsayed10** [comment]
Hi, could you please re-submit a PR with the newest information?

**Pull request closed without merging**
