### PR TITLE
Hobit App

### PR DESCRIPTION
**Pull request by binarybard-dvk**
Hobit App submission

### CODE REVIEW

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
the app looks great. i left some reviews on your testflight, please check them and lmk when i can review your app again

https://appstoreconnect.apple.com/apps/6504830094/testflight/screenshots

**Comment by faisalsayed10** [comment]
Please reply here when all the feedback is addressed

**Comment by binarybard-dvk** [comment]
Hi @faisalsayed10 
I incorporated the changes suggested:
```
change log:
Additions: Activity graph
Fixes: Weird first login infinite loading
```

**Comment by binarybard-dvk** [comment]
Hey @faisalsayed10 😄
I added the below changes:
```
Change log:

Additions:
1. Point system using Gemini AI
2. Streak tracking

Fixes:
1. Fix the activity graph rendering
```

**Review by faisalsayed10 — APPROVED** [review]
this is great!

**Pull request merged**
