### PR TITLE
torsion app

### PR DESCRIPTION
**Pull request by drnez**
Contains the README.md for my app 'torsion'. Final feedback would be greatly appreciated!

### CODE REVIEW

**Comment by faisalsayed10** [comment]
image

hmm why is there a white overlay over the entire app

**Comment by drnez** [comment]
Should I remove the top bar?

**Comment by faisalsayed10** [comment]
no not that, the entire screen looks faded for some reason as if there's an overlay over it?

**Comment by drnez** [comment]
Ah I had added a slight gradient. Is this better?image

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
hey @drnez! I feel like the UI is very basic right now and isn't appealing for the users to use. I would like to see a great UI that looks production-grade before we can proceed with the grant

**Comment by drnez** [comment]
I changed some colours, text sizes and positions, made a new button theme and moved logout to the top right (among more minor tweaks). It seems to have really improved the look - please do let me know if any further changes are needed, UI has never been my strong side :).https://github.com/user-attachments/assets/dec17e89-35a8-42ad-9fc4-f080bcddbfda

**Comment by faisalsayed10** [comment]
Hey @drnez! Totally understand that, here are some specific feedbacks I have. If you can _just_ fix these issues, we'll be good to go :))

image

image

image

image

**Comment by drnez** [comment]
Hi, thanks a lot for that - it was really useful, and I definitely wouldn't have been able to think of it all myself!

Is this the type of thing you're looking for on the 'Select Team' screen?
image

**Comment by drnez** [comment]
I made the requested changes:
https://github.com/user-attachments/assets/b6b1071c-c773-4fa2-ad22-b8d7016d634c

As always feedback would be really appreciated, thanks again for the guidance above - it really was very useful!

**Review by faisalsayed10 — APPROVED** [review]
This is great, this is what I was looking for :)

**Pull request merged**
