### PR TITLE
Add Booklove to Cider 

### PR DESCRIPTION
**Pull request by MoPaMo**
(see README)

### CODE REVIEW

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
I just left two small reviews on TestFlight. Everything else looks good to me! Ready to approve once the reviews are resolved :))

**Comment by MoPaMo** [comment]
Hi!

> I just left two small reviews on TestFlight. Everything else looks good to me! Ready to approve once the reviews are resolved :))

Books marked as saved will appear in your Book List (in the bottom bar) and quotes you like will be used +to +improve +the algorithms, e. g. what you like. 
The Feed Recommendation Algorithm is just a random pick of books for now, but that's because I'm missing user data to "train" usable algorithms, plus its server, side… (You seeing the same book multiple times in a row is weird though, maybe I was working on the server and it that lead to issues, idk…)

**Comment by faisalsayed10** [comment]
okay sounds good

**Comment by faisalsayed10** [comment]
have u completed student ID verification btw?

**Comment by MoPaMo** [comment]
> have u completed student ID verification btw?

Not sure, I can send you my student ID via slack if you want

**Pull request merged**
