### PR TITLE
Add minichef

### PR DESCRIPTION
**Pull request by CoolCoderSJ**

### CODE REVIEW

**Comment by CoolCoderSJ** [comment]
I should note the latest version (v1.0.0) on testflight has been submitted but hasn't been approved just yet, so testflight only shows an older version for now

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
leaving reviews as testflight feedback, please take a look on apple developer portal

**Comment by CoolCoderSJ** [comment]
got it
didn't realize you were still reviewing, if you see a v1.0.1 just ignore it

**Comment by CoolCoderSJ** [comment]
Also, for one of the feedback options, you mentioned you're unsure what the apple button does and takes too much space
agreed it takes too much space but is it not doing anything
it should pull up a panel with all the ingredients

**Comment by faisalsayed10** [comment]
@CoolCoderSJ have u submitted a new version yet? so that i can test it again?

**Comment by CoolCoderSJ** [comment]
Not yet, travelling in 2 days, will be able to work on the app after that

**Comment by faisalsayed10** [comment]
Please reply here when all the feedback is addressed

**Comment by CoolCoderSJ** [comment]
Ah sorry, all the feedback has been addressed and republished as version 1.1.0

**Comment by faisalsayed10** [comment]
left reviews as testflight feedback, please take a look on apple developer portal

**Comment by CoolCoderSJ** [comment]
updated with changes as v1.1.1

**Review by faisalsayed10 — APPROVED** [review]
looks good to me. still there might be UI/UX fixes, improvements at places, but I think you can do simultaneously after approval

**Comment by faisalsayed10** [comment]
@CoolCoderSJ have u completed student ID verification w/ hackclub?

**Comment by CoolCoderSJ** [comment]
yes

**Pull request merged**
