### PR TITLE
Add Waffle Chat

### PR DESCRIPTION
**Pull request by ayaangrover**
I have added my app, Waffle! (It isn't perfect yet, the users button doesn't work so you can't see the users page, but I previewed the users page and it looks great by itself. Unfortunately I won't be able to fix this for 8 days, because I borrow my dad's Mac and he's on a business trip right now.)

### CODE REVIEW

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
Feel like its a very minimal and basic chat app. I would love to see more features like file uploads or creating rooms and inviting folks to those rooms to chat with them

**Comment by ayaangrover** [comment]
I have added the feature to display pngs, jpgs, jpegs, and gifs when a link to their image is sent in the message, as well as converting YouTube video links to thumbnails. I'll try and add the feature to upload your own images from the photos library, and I'll see if I can use different encryptions for each chat, and every message with a different encryption method will be hidden, thus resulting in different "channels" of communication. Thanks!

**Comment by KrishOnGH** [comment]
hmm all i like is the name

**Comment by KrishOnGH** [comment]
im kidding ayaans my friend gud job buddy

**Comment by faisalsayed10** [comment]
Would love to see the ability to create chat rooms and create invite links / invite specific emails, usernames to those chat rooms

**Comment by ayaangrover** [comment]
Hey Faisal! I've finally finished the application! You can now create rooms, add members to rooms upon initialization, and add members to rooms after the room's creation. In an upcoming release, I will add email notifications(if somebody adds you to a room), the ability to remove people from a room, and fixing the users page. I've updated the TestFlight link, so you'll have to try the new link(I deleted the old one by mistake), and I just added the new build to the Waffle External Testers group. Let me know what you think!

**Review by faisalsayed10 — APPROVED** [review]

**Pull request merged**
