### PR TITLE
Queuify App

### PR DESCRIPTION
**Pull request by jenniferZO**
This is my app submission for Queuify. 
Queuify is a iOS app where users join a digital queue for a destination. It allows users to move through a line without physically being there, allowing them to do other activites simultaneously. Users can now save and enjoy more time during holidays and less time in the queue.

### CODE REVIEW

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
hi i feel like a good amount of work needs to be done on the app before it can be ready for the final review

**Comment by faisalsayed10** [comment]
Please reply here when all the feedback is addressed

**Comment by jenniferZO** [comment]
More recent and updated files in this repository. 
https://github.com/jenniferZO/Queuify_XcodeSwiftApp

**Comment by faisalsayed10** [comment]
@jenniferZO please push a new build to testflight so i can test it again :)

**Comment by jenniferZO** [comment]
Queuify has been updated with new features and is ready for submission.

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
I left some reviews on Testflight, please check those

**Review by faisalsayed10 — APPROVED** [review]

**Pull request merged**
